name: Merge
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          pull-request-title-pattern: "chore: release ${version}"
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.20"
        if: ${{ steps.release.outputs.release_created }}
      - run: bun add -g npm
        if: ${{ steps.release.outputs.release_created }}
      - run: bun install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: bun run build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
